[[using.auto-configuration]]
= Auto-configuration

* == -- based on the .jar dependencies -> configure automatically your Spring application
    ** _Example:_ if `HSQLDB` is on your classpath and you have NOT manually configured any database connection beans -> Spring Boot auto-configures an in-memory database
* ways
    ** `@EnableAutoConfiguration` | 1! of your `@Configuration` classes or
    ** `@SpringBootApplication` | 1! of your `@Configuration` classes

[[using.auto-configuration.replacing]]
== Gradually Replacing Auto-configuration

* uses
    ** you want to customize / specific parts of the auto-configuration are replaced
* _Example:_ , add your own `DataSource` bean
* start with `--debug`
    ** ways -- TODO: Check in some real example --
        *** `mvnDebug spring-boot:run`
        *** `./gradlew bootRun --debug-jvm`
    ** allows
        *** checking what auto-configuration is currently being applied

[[using.auto-configuration.disabling-specific]]
== Disabling Specific Auto-configuration Classes

* ways -- can be applied at the same time --
    ** `@SpringBootApplication(exclude = ....)` or `@EnableAutoConfiguration(exclude = ....)`
        *** disable auto-configuration classes / are in the classpath
        *** _Example:_

        include-code::MyApplication[]

    ** `@SpringBootApplication(excludeName = fullyQualifiedName)` or `@EnableAutoConfiguration(excludeName = ....)`
        *** disable auto-configuration classes / are ðŸ‘ï¸ NOT in the classpath ðŸ‘ï¸
    ** `spring.autoconfigure.exclude=....`
        *** list the auto-configuration classes to exclude
* auto-configuration classes
    ** âš ï¸ï¸are public, BUT name of the class is the only aspect, public API âš ï¸

[[using.auto-configuration.packages]]
== Auto-configuration Packages

* := packages / various auto-configured features look when scanning for things (_Example:_ entities and Spring Data repositories)
    ** _Example:_ `@EnableAutoConfiguration` -> determines the default auto-configuration package
* `@AutoConfigurationPackage`
    ** allows
        *** configuring additional packages
