[[using.structuring-your-code]]
= Structuring Your Code

* ðŸ‘ï¸ NOT required by Spring Boot ðŸ‘ï¸
* https://spring.io/projects/spring-modulith#overview[Spring Modulith]
    ** enforce structure -- based on -- domains

[[using.structuring-your-code.using-the-default-package]]
== Using the "`default`" Package

* uses
    ** class does NOT include a `package` declaration
* recommendation
    ** avoided
        *** == declare always
        *** Reason: ðŸ§  for Spring Boot applications / use `@ComponentScan`, `@ConfigurationPropertiesScan`, `@EntityScan`, or `@SpringBootApplication` -> every class from every .jar is read -> it can cause particular problems ðŸ§ 
    ** follow Java's recommended package naming conventions & reversed domain name ( _Example:_ `com.example.project`)



[[using.structuring-your-code.locating-the-main-class]]
== Locating the Main Application Class

* recommendation
    ** main application class in a root package above other classes
        *** -> component scan -- is applied -- only on your project
    ** xref:using/using-the-springbootapplication-annotation.adoc[`@SpringBootApplication` annotation] oftenly placed on your main class
        *** -> defines a base "`search package`" / certain items
            **** _Example:_ if you are writing a JPA application -> the package of the `@SpringBootApplication` annotated class -- is used to search for -- `@Entity` items
* _Example:_  typical layout

[source]
----
com
 +- example
     +- myapplication
         +- MyApplication.java
         |
         +- customer
         |   +- Customer.java
         |   +- CustomerController.java
         |   +- CustomerService.java
         |   +- CustomerRepository.java
         |
         +- order
             +- Order.java
             +- OrderController.java
             +- OrderService.java
             +- OrderRepository.java
----
    ** `MyApplication.java` would declare the `main` method + `@SpringBootApplication`

        include-code::MyApplication[]
