[[howto.actuator]]
= Actuator

Spring Boot Actuator


[[howto.actuator.change-http-port-or-address]]
== Change the HTTP Port or Address of the Actuator Endpoints

* if standalone application -> Actuator
    ** HTTP port (defaults) == main HTTP port
    ** if you want different HTTP port -> set `management.server.port`
    ** if you want different network address -> set `management.server.address=validIPAddressToWhichServerCanBind`
    ** Check
        *** xref:api:java/org/springframework/boot/actuate/autoconfigure/web/server/ManagementServerProperties.html[`ManagementServerProperties`] source code
        *** xref:reference:actuator/monitoring.adoc#actuator.monitoring.customizing-management-server-port[Customizing the Management Server Port] in the "`Production-Ready Features`" section


[[howto.actuator.customize-whitelabel-error-page]]
== Customize the '`whitelabel`' Error Page
* '`whitelabel`' error page
    ** installed by Spring Boot
    ** if you encounter a server error &
        *** browser client -> '`whitelabel`' error page displayed
        *** machine clients / consuming JSON and other media types -> sensible response / right error code
    ** if you set `server.error.whitelabel.enabled=false`  -> ðŸ‘ï¸switch off the default error page ðŸ‘ï¸ ->
        *** you must handle it / exists `BeanNameViewResolver` in your `ApplicationContext` (== `@Bean` named `error`)
            **** Reason: ðŸ§  Spring Boot still tries to resolve the error view ðŸ§ 
            **** overriding the error -- via -- templating technology
                ***** Thymeleaf -- adding an -- `error.html` template
                ***** FreeMarker -- adding an -- `error.ftlh` template
            **** `View` / -- resolves with a name of -- `error` OR
            **** `@Controller` / handles the `/error` path
            **** Check
                ***** {code-spring-boot-autoconfigure-src}/web/servlet/error/ErrorMvcAutoConfiguration.java[`ErrorMvcAutoConfiguration`] for more options
                ***** xref:reference:web/servlet.adoc#web.servlet.spring-mvc.error-handling[] -- how to register handlers in the servlet container?



[[howto.actuator.customizing-sanitization]]
== Customizing Sanitization
* TODO:
To take control over the sanitization, define a `SanitizingFunction` bean.
The `SanitizableData` with which the function is called provides access to the key and value as well as the `PropertySource` from which they came.
This allows you to, for example, sanitize every value that comes from a particular property source.
Each `SanitizingFunction` is called in order until a function changes the value of the sanitizable data.



[[howto.actuator.map-health-indicators-to-metrics]]
== Map Health Indicators to Micrometer Metrics

Spring Boot health indicators return a `Status` type to indicate the overall system health.
If you want to monitor or alert on levels of health for a particular application, you can export these statuses as metrics with Micrometer.
By default, the status codes "`UP`", "`DOWN`", "`OUT_OF_SERVICE`" and "`UNKNOWN`" are used by Spring Boot.
To export these, you will need to convert these states to some set of numbers so that they can be used with a Micrometer `Gauge`.

The following example shows one way to write such an exporter:

include-code::MyHealthMetricsExportConfiguration[]
