[[howto.application]]
= Spring Boot Application

This section includes topics relating directly to Spring Boot applications.



[[howto.application.failure-analyzer]]
== Create Your Own FailureAnalyzer

xref:api:java/org/springframework/boot/diagnostics/FailureAnalyzer.html[`FailureAnalyzer`] is a great way to intercept an exception on startup and turn it into a human-readable message, wrapped in a xref:api:java/org/springframework/boot/diagnostics/FailureAnalysis.html[`FailureAnalysis`].
Spring Boot provides such an analyzer for application-context-related exceptions, JSR-303 validations, and more.
You can also create your own.

`AbstractFailureAnalyzer` is a convenient extension of `FailureAnalyzer` that checks the presence of a specified exception type in the exception to handle.
You can extend from that so that your implementation gets a chance to handle the exception only when it is actually present.
If, for whatever reason, you cannot handle the exception, return `null` to give another implementation a chance to handle the exception.

`FailureAnalyzer` implementations must be registered in `META-INF/spring.factories`.
The following example registers `ProjectConstraintViolationFailureAnalyzer`:

[source,properties]
----
org.springframework.boot.diagnostics.FailureAnalyzer=\
com.example.ProjectConstraintViolationFailureAnalyzer
----

NOTE: If you need access to the `BeanFactory` or the `Environment`, declare them as constructor arguments in your `FailureAnalyzer` implementation.



[[howto.application.troubleshoot-auto-configuration]]
== Troubleshoot Auto-configuration

The Spring Boot auto-configuration tries its best to "`do the right thing`", but sometimes things fail, and it can be hard to tell why.

There is a really useful `ConditionEvaluationReport` available in any Spring Boot `ApplicationContext`.
You can see it if you enable `DEBUG` logging output.
If you use the `spring-boot-actuator` (see the xref:actuator.adoc[] section), there is also a `conditions` endpoint that renders the report in JSON.
Use that endpoint to debug the application and see what features have been added (and which have not been added) by Spring Boot at runtime.

Many more questions can be answered by looking at the source code and the API documentation.
When reading the code, remember the following rules of thumb:

* Look for classes called `+*AutoConfiguration+` and read their sources.
  Pay special attention to the `+@Conditional*+` annotations to find out what features they enable and when.
  Add `--debug` to the command line or the System property `-Ddebug` to get a log on the console of all the auto-configuration decisions that were made in your app.
  In a running application with actuator enabled, look at the `conditions` endpoint (`/actuator/conditions` or the JMX equivalent) for the same information.
* Look for classes that are `@ConfigurationProperties` (such as xref:api:java/org/springframework/boot/autoconfigure/web/ServerProperties.html[`ServerProperties`]) and read from there the available external configuration options.
  The `@ConfigurationProperties` annotation has a `name` attribute that acts as a prefix to external properties.
  Thus, `ServerProperties` has `prefix="server"` and its configuration properties are `server.port`, `server.address`, and others.
  In a running application with actuator enabled, look at the `configprops` endpoint.
* Look for uses of the `bind` method on the `Binder` to pull configuration values explicitly out of the `Environment` in a relaxed manner.
  It is often used with a prefix.
* Look for `@Value` annotations that bind directly to the `Environment`.
* Look for `@ConditionalOnExpression` annotations that switch features on and off in response to SpEL expressions, normally evaluated with placeholders resolved from the `Environment`.



[[howto.application.customize-the-environment-or-application-context]]
== Customize the Environment or ApplicationContext Before It Starts

* `ApplicationListeners` and `ApplicationContextInitializers`
    ** allows
        *** -- applying customizations to -- context or environment
    ** Check xref:reference:features/spring-application.adoc#features.spring-application.application-events-and-listeners[]
* ways to register customizations
    ** Spring Boot -- loads from -- `META-INF/spring.factories`
    ** programmatically / application
        *** == before you run `SpringApplication` -- call to the methods --  `addListeners` and `addInitializers`
    ** declaratively / all applications by
        *** adding a `META-INF/spring.factories`
            **** for `Environment` -- via -- `EnvironmentPostProcessor`

                [source]
                ----
                org.springframework.boot.env.EnvironmentPostProcessor=com.example.YourEnvironmentPostProcessor
                ----

                ***** _Example:_ loads a .yaml -- from the -- classpath

                    include-code::MyEnvironmentPostProcessor[]

        *** packaging a ".jar" / ALL applications use as a library
* `Environment`
    ** ðŸ‘ï¸already prepared with ALL the usual property sources / Spring Boot -- loads -- by default ðŸ‘ï¸
        *** -> -- from the environment -- possible to get the location of the file
    ** ðŸ‘ï¸ `@PropertySource` -- is NOT the recommended way to load -- a custom resource in the `Environment` ðŸ‘ï¸
        *** Reason: ðŸ§  Once application context is being refreshed -> it's added ðŸ§ 
            **** -> too late to configure certain properties / are read before refresh begins -- _Example:_ `+logging.*+` and `+spring.main.*+` --

[[howto.application.context-hierarchy]]
== Build an ApplicationContext Hierarchy (Adding a Parent or Root Context)

You can use the `ApplicationBuilder` class to create parent/child `ApplicationContext` hierarchies.
See xref:reference:features/spring-application.adoc#features.spring-application.fluent-builder-api[] in the "`Spring Boot Features`" section for more information.



[[howto.application.non-web-application]]
== Create a Non-web Application

Not all Spring applications have to be web applications (or web services).
If you want to execute some code in a `main` method but also bootstrap a Spring application to set up the infrastructure to use, you can use the `SpringApplication` features of Spring Boot.
A `SpringApplication` changes its `ApplicationContext` class, depending on whether it thinks it needs a web application or not.
The first thing you can do to help it is to leave server-related dependencies (such as the servlet API) off the classpath.
If you cannot do that (for example, if you run two applications from the same code base) then you can explicitly call `setWebApplicationType(WebApplicationType.NONE)` on your `SpringApplication` instance or set the `applicationContextClass` property (through the Java API or with external properties).
Application code that you want to run as your business logic can be implemented as a `CommandLineRunner` and dropped into the context as a `@Bean` definition.
