[[howto.hotswapping]]
= Hot Swapping / Hot Reloading

Supported by Spring Boot

[[howto.hotswapping.reload-static-content]]
== Reload Static Content
* There are several options
    ** xref:reference:using/devtools.adoc[`spring-boot-devtools`]
        *** Recommended
            **** Reason: 🧠 provides additional development-time features -- _Example:_ support for fast application restarts and LiveReload, sensible development-time configuration (such as template caching) 🧠
* if you want that static resource changes take effect -> you must "build"
    ** based on the IDE
        *** [Eclipse] once you save the file -> run it automatically
        *** [IntelliJ IDEA] Make Project command -- triggers the -- necessary build
    ** == changes to static resources
        *** -- do NOT trigger a -- restart of your application
            **** Reason: 🧠 xref:reference:using/devtools.adoc#using.devtools.restart.excluding-resources[default restart exclusions] 🧠
        *** trigger a live reload ❓
* ALL modern IDEs
    ** allow
        *** reloading of static resources
        *** usually hot-swapping of Java class changes
* xref:build-tool-plugin:index.adoc[Maven and Gradle plugins]
    ** -- can be configured ( `addResources` property) to support --
        *** running from the CL / reloading static files from source
    ** + external css/js compiler process -- if you are writing that code with higher-level tools



[[howto.hotswapping.reload-templates]]
== Reload Templates without Restarting the Container

Most of the templating technologies supported by Spring Boot include a configuration option to disable caching (described later in this document).
If you use the `spring-boot-devtools` module, these properties are xref:reference:using/devtools.adoc#using.devtools.property-defaults[automatically configured] for you at development time.



[[howto.hotswapping.reload-templates.thymeleaf]]
=== Thymeleaf Templates

If you use Thymeleaf, set `spring.thymeleaf.cache` to `false`.
See {code-spring-boot-autoconfigure-src}/thymeleaf/ThymeleafAutoConfiguration.java[`ThymeleafAutoConfiguration`] for other Thymeleaf customization options.



[[howto.hotswapping.reload-templates.freemarker]]
=== FreeMarker Templates

If you use FreeMarker, set `spring.freemarker.cache` to `false`.
See {code-spring-boot-autoconfigure-src}/freemarker/FreeMarkerAutoConfiguration.java[`FreeMarkerAutoConfiguration`] for other FreeMarker customization options.



[[howto.hotswapping.reload-templates.groovy]]
=== Groovy Templates

If you use Groovy templates, set `spring.groovy.template.cache` to `false`.
See {code-spring-boot-autoconfigure-src}/groovy/template/GroovyTemplateAutoConfiguration.java[`GroovyTemplateAutoConfiguration`] for other Groovy customization options.



[[howto.hotswapping.fast-application-restarts]]
== Fast Application Restarts

The `spring-boot-devtools` module includes support for automatic application restarts.
While not as fast as technologies such as https://www.jrebel.com/products/jrebel[JRebel] it is usually significantly faster than a "`cold start`".
You should probably give it a try before investigating some of the more complex reload options discussed later in this document.

For more details, see the xref:reference:using/devtools.adoc[] section.



[[howto.hotswapping.reload-java-classes-without-restarting]]
== Reload Java Classes without Restarting the Container

Many modern IDEs (Eclipse, IDEA, and others) support hot swapping of bytecode.
Consequently, if you make a change that does not affect class or method signatures, it should reload cleanly with no side effects.
