[[upgrading]]
= Upgrading Spring Boot

* how to upgrade from earlier versions of Spring Boot
    ** {url-github-wiki}[wiki]
* Upgrading instructions are first item | release notes
* If you are >1 release behind -> review ALL the release notes of the versions that you jumped

[[upgrading.from-1x]]
== Upgrading From 1.x

* If you are upgrading from the `1.x` release of Spring Boot -> check
    ** {url-github-wiki}/Spring-Boot-2.0-Migration-Guide[migration guide]
    ** {url-github-wiki}[release notes]

[[upgrading.to-feature]]
== Upgrading to a New Feature Release

* how does it work?
    ** analyze your application's environment
        *** ⚠️properties / added late | environment -> NOT taken in account ⚠️-- _Example:_ `@PropertySource`
    ** print diagnostics | startup
    ** temporarily migrate properties | runtime
* add | your project

[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-properties-migrator</artifactId>
	<scope>runtime</scope>
</dependency>
----

* Once you finish the migration -> remove this module from your project's dependencies

[[upgrading.cli]]
== Upgrading the Spring Boot CLI

To upgrade an existing CLI installation, use the appropriate package manager command (for example, `brew upgrade`).
If you manually installed the CLI, follow the xref:installing.adoc#getting-started.installing.cli.manual-installation[standard instructions], remembering to update your `PATH` environment variable to remove any older references.
