[[features.task-execution-and-scheduling]]
= Task Execution and Scheduling

* if there is NO `Executor` bean | context -> Spring Boot auto-configures an `AsyncTaskExecutor`
    ** 👀if virtual threads are enabled -> `AsyncTaskExecutor` -- will be a --  `SimpleAsyncTaskExecutor` / uses virtual threads 👀
        *** way to enable virtual threads
            **** use Java v21+ &
            **** `spring.threads.virtual.enabled=true` .
    ** 👀by default, `AsyncTaskExecutor` -- will be a -- `ThreadPoolTaskExecutor` / sensible defaults 👀
        *** by default, thread pool uses 8 core threads
            **** / -- can, according to the load --
                ***** grow
                ***** shrink
                    ****** == if the demand for threads decreases (== tasks complete) -> the thread pool reclaims idle threads -- after a -- certain period of time (by default, 60s)
            **** if you want to customize it -> specify `spring.task.execution`

                [configprops,yaml]
                ----
                spring:
                  task:
                    execution:
                      pool:
                        # if the queue is full (100 tasks) -> thread pool -- increases to -- maximum 16 threads
                        max-size: 16
                        queue-capacity: 100
                        keep-alive: "10s"
                ----

    ** `AsyncTaskExecutor` is used for
        *** asynchronous task execution
            **** == `@EnableAsync`
        *** Spring for GraphQL's asynchronous handling of `Callable` return values -- from -- controller methods
        *** Spring MVC's asynchronous request processing
        *** Spring WebFlux's blocking execution support
* if you have defined a custom `Executor` | context -> it will be used by
    ** regular task execution (== `@EnableAsync`)
    ** Spring for GraphQL
    ** if it's an `AsyncTaskExecutor` implementation (named `applicationTaskExecutor`)
        *** -> ALSO used by
            **** Spring MVC
            **** Spring WebFlux
        *** coexistence of `Executor` & `AsyncTaskExecutor` -- depends on -- your target arrangement
            **** `Executor` -- can be changed into an -- `AsyncTaskExecutor`
            **** both an `AsyncTaskExecutor` and an `AsyncConfigurer` / wrap your custom `Executor`
* auto-configured `ThreadPoolTaskExecutorBuilder`
    ** allows
        *** creating instances / reproduce what the auto-configuration does by default
* if scheduler needs to be associated -- with -- scheduled task execution -> it's auto-configured
    ** _Example for this association:_ use `@EnableScheduling`
    ** if virtual threads are enabled -> scheduler -- will be a -- `SimpleAsyncTaskScheduler` /
        *** uses virtual threads
        *** ignore any pooling related properties
    ** by default, scheduler -- will be a -- `ThreadPoolTaskScheduler` / sensible defaults
        *** 1 thread by default
        *** if you want to customize it -> specify `spring.task.scheduling`

            [configprops,yaml]
            ----
            spring:
              task:
                scheduling:
                  thread-name-prefix: "scheduling-"
                  pool:
                    size: 2
            ----

* if a custom executor OR scheduler needs to be created -> available | context
    ** `ThreadPoolTaskExecutorBuilder` bean
    ** `SimpleAsyncTaskExecutorBuilder` bean
    ** `ThreadPoolTaskSchedulerBuilder` bean
    ** `SimpleAsyncTaskSchedulerBuilder` bean
* if virtual threads are enabled -> beans / auto-configured -- to use -- them
    ** `SimpleAsyncTaskExecutorBuilder`
    ** `SimpleAsyncTaskSchedulerBuilder`
